name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: kartoza/postgis:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1
          elixir-version: 1.10.2
      - name: Run Mix project tests
        run: |
          mix deps.get
          mix compile --warnings-as-errors
          mix format --dry-run --check-formatted
          mix test
